language: node_js
node_js:
  - 'stable'
before_script:
  - npm install
script:
  - npm run lint
  - npm run lint:ruc
  - npm run test
  - npm run test:ruc
  - npm run build:prod
  - npm run build:ruc:prod
before_deploy:
  - cd dist/sunat/ruc
deploy:
  provider: npm
  email: $EMAIL
  api_key: $AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: @sunat/ruc
